ALTER TABLE canonical_entities ADD COLUMN entity_type TEXT;
ALTER TABLE canonical_entities ADD COLUMN source TEXT;
ALTER TABLE canonical_entities ADD COLUMN confidence REAL;
ALTER TABLE canonical_entities ADD COLUMN valid_from TEXT;
ALTER TABLE canonical_entities ADD COLUMN valid_to TEXT;
ALTER TABLE canonical_entities ADD COLUMN valid_to_state TEXT NOT NULL DEFAULT 'unspecified';
ALTER TABLE canonical_entities ADD COLUMN tags TEXT NOT NULL DEFAULT '[]';
ALTER TABLE canonical_entities ADD COLUMN produced_by TEXT;
ALTER TABLE canonical_entities ADD COLUMN about TEXT;
ALTER TABLE canonical_entities ADD COLUMN affects TEXT;
ALTER TABLE canonical_entities ADD COLUMN specificity TEXT;
ALTER TABLE canonical_entities ADD COLUMN updated_at TEXT NOT NULL DEFAULT (datetime('now'));
